# https://krpc.github.io/krpc/cpp/api/space-center/orbit.html

string body     # name of the body, not the object
float64 apoapsis
float64 periapsis
float64 apoapsis_altitude
float64 periapsis_altitude
float64 semi_major_axis
float64 semi_minor_axis
float64 radius
float64 speed
float64 period
float64 time_to_apoapsis
float64 time_to_periapsis
float64 eccentricity
float64 inclination
float64 longitude_of_ascending_node
float64 argument_of_periapsis
float64 mean_anomaly_at_epoch
float64 epoch
float64 mean_anomaly
float64 eccentric_anomaly
float64 true_anomaly
float64 orbital_speed
float64 time_to_soi_change
